jwt.secret=vmfhaltkwkd79s457s89f7s987f9s87f9s87f9s87fwe7f89s7f98s7f98s7f98s7f98s7f98s7f98s7f
jwt.expiration=86400000
jwt.refresh-expiration=604800000
weather.serviceKey=a207655624f95b51e6f65832d7f073810519fd182bb1fa36e3c8392e9fbd7326
weather.sht.url=http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getVilageFcst
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=test
spring.mail.password=test
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
